// <auto-generated>
//   Tools/CardShapeGen/gen_fxpet_card_shapes.py 가
//   design/equipment/verify/r20_coords.txt 의 (다)군 12종 `-- CARD` 절에서 굽는다.
//   설계 정본: docs/EQUIPMENT_HANDOFF_PORT_SPEC.md §14-12-3 · §14-12-5 #23/#26/#27.
//   ★ 손으로 고치지 마라 — 고칠 것은 좌표 전문이고, 생성기가 왕복 검산을 함께 찍는다.
//   ★ 좌표 단위: 머리 중심 원점 · R 배수 · y 위(전문은 64u 아이콘 단위 · y 아래).
//      되돌리는 프레이밍은 §14-12-5 #22 가 전체 상자 카드를 위해 선언한 1 R = 16.0f u ·
//      머리 중심 (32.0f, 30.0f) 이다(FX/PET 에는 인계본 슬롯 박스가 없다).
//   ★ 표면: **카드 전용**(AccessorySurface.Card). 몸(월드) FX/PET 도형은
//      Interaction/AppearanceShapeBuilder.cs 소관이고 이 파일은 거기에 한 점도 넣지 않는다.
// </auto-generated>
using System.Collections.Generic;
using UnityEngine;
using StickMate.Core;

namespace StickMate.Interaction
{
    internal static partial class AccessoryShapeBuilder
    {
        /// <summary>
        /// (다)군 12종의 <b>카드 아이콘</b> 조각. 사용자 신고 2026-09-06 <i>"펫들도 아직 업데이트가
        /// 안되어 있는데"</i> — 이펙트·펫 카드만 옛 40u 폴백(<c>AccessoryDefSO.icon</c>)으로 남아
        /// 나머지 30종과 <b>채움·잉크 윤곽·하이라이트·획 폭</b> 넷이 달랐다(§14-12-5 #23).
        ///
        /// <para>여기 있는 것은 <b>카드뿐</b>이다. 착용했을 때 화면에 뜨는 이펙트·펫 본체는 여전히
        /// <see cref="AppearanceShapeBuilder"/>가 만든다 — §14-12-5 #23 이 "몸 효과·펫은 현행
        /// <c>AppearanceShapeBuilder</c> 그대로, 카드만 갈라진다"고 못박았고, 그 근거는 리더 승인
        /// 규칙 39-P(입자의 정체는 한 알의 모양이 아니라 여럿이 만드는 무늬 —
        /// <see cref="AppearanceShapeBuilder"/> 문서)다.</para>
        ///
        /// <para>★ 그래도 <b>색과 위상</b>은 월드를 따른다. 2026-09-06 R22 가 월드에서 확정한 두 건
        /// (반짝임 오목비 <see cref="AppearanceShapeBuilder.SparkleConcaveRatio"/> · 커서친구
        /// 머리/꼬리 2색 분할)은 생성기가 기계적으로 카드에 옮긴다. 안 옮기면 "카드에 없는 색이
        /// 착용하면 나타난다"는 이 저장소의 반복 결함이 그 자리에서 다시 열린다.</para>
        /// </summary>
        private static bool AppendFxPetCard(List<Shape> sink, EquipmentSlot slot, int item,
            in Rig rig, AccessorySurface surface)
        {
            // 몸 표면에는 아무것도 넣지 않는다. 이 한 줄이 「FX/PET 은 몸 도형이 없다」는 사실을
            // 계속 참으로 유지한다 — 이 파일이 통째로 틀려도 캐릭터 위에는 아무 일도 일어나지 않는다.
            if (surface != AccessorySurface.Card) return false;

            switch (slot)
            {
                case EquipmentSlot.Fx: return AppendFxCard(sink, item, rig);
                case EquipmentSlot.Pet: return AppendPetCard(sink, item, rig);
                default: return false;
            }
        }

        private static bool AppendFxCard(List<Shape> sink, int item, in Rig rig)
        {
            switch (item)
            {
                case AppearanceShapeBuilder.FxNone:   // 없음 — 조각 2
                    FxPetCardPiece(sink, rig, "fxnone.CB0", FxPetCard_fx_none_CB0, loop: true, filled: false, tone: 4, strokeMult: 1f, noStroke: false, lineAlpha: 1f, underBack: 0);   // 빈 고리(잉크 선) — 「없음」
                    FxPetCardPiece(sink, rig, "fxnone.S1", FxPetCard_fx_none_S1, loop: false, filled: false, tone: 4, strokeMult: 1f, noStroke: false, lineAlpha: 1f, underBack: 0);   // 빗금
                    return true;
                case AppearanceShapeBuilder.FxFootprint:   // 발자국 — 조각 4
                    FxPetCardPiece(sink, rig, "footprint.B0", FxPetCard_fx_footprint_B0, loop: true, filled: true, tone: 0, strokeMult: 1f, noStroke: false, lineAlpha: 1f, underBack: 0);   // 발바닥(M InkTone + 잉크)
                    FxPetCardPiece(sink, rig, "footprint.CB1", FxPetCard_fx_footprint_CB1, loop: true, filled: true, tone: 0, strokeMult: 1f, noStroke: false, lineAlpha: 1f, underBack: 0);   // 엄지발가락
                    FxPetCardPiece(sink, rig, "footprint.S2", FxPetCard_fx_footprint_S2, loop: false, filled: false, tone: 4, strokeMult: 1f, noStroke: false, lineAlpha: 0.5f, underBack: 2);   // 발 허리 주름(잉크 α0.5)
                    FxPetCardPiece(sink, rig, "footprint.H3", FxPetCard_fx_footprint_H3, loop: false, filled: false, tone: 3, strokeMult: 0.75f, noStroke: false, lineAlpha: 0.42f, underBack: 3);   // 하이라이트
                    return true;
                case AppearanceShapeBuilder.FxSparkle:   // 반짝임 — 조각 4
                    FxPetCardPiece(sink, rig, "sparkle.B0", FxPetCard_fx_sparkle_B0, loop: true, filled: true, tone: 0, strokeMult: 1f, noStroke: false, lineAlpha: 1f, underBack: 0);   // 큰 별(M Gold + 잉크)
                    FxPetCardPiece(sink, rig, "sparkle.CF1", FxPetCard_fx_sparkle_CF1, loop: true, filled: true, tone: 1, strokeMult: 1f, noStroke: true, lineAlpha: 1f, underBack: 0);   // 작은 별(M2 GoldLight, 윤곽 없음)
                    FxPetCardPiece(sink, rig, "sparkle.S2", FxPetCard_fx_sparkle_S2, loop: false, filled: false, tone: 1, strokeMult: 1.2f, noStroke: false, lineAlpha: 1f, underBack: 0);   // 빛 점(독립선 M2)
                    FxPetCardPiece(sink, rig, "sparkle.H3", FxPetCard_fx_sparkle_H3, loop: false, filled: false, tone: 3, strokeMult: 0.75f, noStroke: false, lineAlpha: 0.42f, underBack: 0);   // 하이라이트
                    return true;
                case AppearanceShapeBuilder.FxDust:   // 먼지구름 — 조각 4
                    FxPetCardPiece(sink, rig, "dust.B0", FxPetCard_fx_dust_B0, loop: true, filled: true, tone: 0, strokeMult: 1f, noStroke: false, lineAlpha: 1f, underBack: 0);   // 먼지구름(M InkDimTone + 잉크)
                    FxPetCardPiece(sink, rig, "dust.CB1", FxPetCard_fx_dust_CB1, loop: true, filled: true, tone: 1, strokeMult: 1f, noStroke: false, lineAlpha: 1f, underBack: 0);   // 작은 뭉치(M2 InkTone)
                    FxPetCardPiece(sink, rig, "dust.CB2", FxPetCard_fx_dust_CB2, loop: true, filled: true, tone: 1, strokeMult: 1f, noStroke: false, lineAlpha: 1f, underBack: 0);   // 작은 뭉치
                    FxPetCardPiece(sink, rig, "dust.H3", FxPetCard_fx_dust_H3, loop: false, filled: false, tone: 3, strokeMult: 0.75f, noStroke: false, lineAlpha: 0.42f, underBack: 3);   // 하이라이트
                    return true;
                case AppearanceShapeBuilder.FxBubble:   // 물방울 — 조각 4
                    FxPetCardPiece(sink, rig, "bubble.CB0", FxPetCard_fx_bubble_CB0, loop: true, filled: true, tone: 0, strokeMult: 1f, noStroke: false, lineAlpha: 1f, underBack: 0);   // 큰 방울(M Blue + 잉크)
                    FxPetCardPiece(sink, rig, "bubble.CB1", FxPetCard_fx_bubble_CB1, loop: true, filled: true, tone: 1, strokeMult: 1f, noStroke: false, lineAlpha: 1f, underBack: 0);   // 작은 방울(M2 DarkLens)
                    FxPetCardPiece(sink, rig, "bubble.CB2", FxPetCard_fx_bubble_CB2, loop: true, filled: true, tone: 1, strokeMult: 1f, noStroke: false, lineAlpha: 1f, underBack: 0);   // 작은 방울
                    FxPetCardPiece(sink, rig, "bubble.H3", FxPetCard_fx_bubble_H3, loop: false, filled: false, tone: 3, strokeMult: 1f, noStroke: false, lineAlpha: 0.42f, underBack: 3);   // 하이라이트(긴 광택 — 방울의 정체)
                    return true;
                case AppearanceShapeBuilder.FxLeaf:   // 나뭇잎 — 조각 4
                    FxPetCardPiece(sink, rig, "leaf.B0", FxPetCard_fx_leaf_B0, loop: true, filled: true, tone: 0, strokeMult: 1f, noStroke: false, lineAlpha: 1f, underBack: 0);   // 잎(M TintNeck + 잉크)
                    FxPetCardPiece(sink, rig, "leaf.S1", FxPetCard_fx_leaf_S1, loop: false, filled: false, tone: 4, strokeMult: 1f, noStroke: false, lineAlpha: 0.45f, underBack: 1);   // 잎맥(잉크 α0.45)
                    FxPetCardPiece(sink, rig, "leaf.S2", FxPetCard_fx_leaf_S2, loop: false, filled: false, tone: 1, strokeMult: 1.2f, noStroke: false, lineAlpha: 1f, underBack: 0);   // 잎자루(독립선 M2 Gold ×1.2)
                    FxPetCardPiece(sink, rig, "leaf.H3", FxPetCard_fx_leaf_H3, loop: false, filled: false, tone: 3, strokeMult: 0.75f, noStroke: false, lineAlpha: 0.42f, underBack: 3);   // 하이라이트
                    return true;
                // ★ 위 여섯 자리가 카탈로그의 FX 전부다(0~5). 정상값은 여기 오지 않는다 —
                //   정상값을 default 로 흘리면 정상 사용자 전원에게 거짓 경보가 찍힌다(FX 0번 사고).
                default:
                    ShapeCoverageGuard.ReportMissingFxShape(item, "AccessoryShapeBuilder.FxPetCard(카드)");
                    return false;
            }
        }

        private static bool AppendPetCard(List<Shape> sink, int item, in Rig rig)
        {
            switch (item)
            {
                case AppearanceShapeBuilder.PetBall:   // 작은공 — 조각 4
                    FxPetCardPiece(sink, rig, "ball.CB0", FxPetCard_pet_ball_CB0, loop: true, filled: true, tone: 0, strokeMult: 1f, noStroke: false, lineAlpha: 1f, underBack: 0);   // 공(M Toy + 잉크)
                    FxPetCardPiece(sink, rig, "ball.S1", FxPetCard_pet_ball_S1, loop: false, filled: false, tone: 1, strokeMult: 1.1f, noStroke: false, lineAlpha: 1f, underBack: 0);   // 솔기(독립선 M2 Paper) — 구(球)의 큰 원
                    FxPetCardPiece(sink, rig, "ball.S2", FxPetCard_pet_ball_S2, loop: false, filled: false, tone: 1, strokeMult: 1.1f, noStroke: false, lineAlpha: 1f, underBack: 0);   // 솔기
                    FxPetCardPiece(sink, rig, "ball.H3", FxPetCard_pet_ball_H3, loop: false, filled: false, tone: 3, strokeMult: 0.75f, noStroke: false, lineAlpha: 0.42f, underBack: 3);   // 하이라이트
                    return true;
                case AppearanceShapeBuilder.PetPlane:   // 종이비행기 — 조각 4
                    FxPetCardPiece(sink, rig, "plane.B0", FxPetCard_pet_plane_B0, loop: true, filled: true, tone: 0, strokeMult: 1f, noStroke: false, lineAlpha: 1f, underBack: 0);   // 윗날개(M Paper + 잉크)
                    FxPetCardPiece(sink, rig, "plane.B1", FxPetCard_pet_plane_B1, loop: true, filled: true, tone: 1, strokeMult: 1f, noStroke: false, lineAlpha: 1f, underBack: 0);   // 아랫날개·용골(M2 Silver + 잉크)
                    FxPetCardPiece(sink, rig, "plane.S2", FxPetCard_pet_plane_S2, loop: false, filled: false, tone: 4, strokeMult: 1f, noStroke: false, lineAlpha: 0.4f, underBack: 0);   // 접은 선(잉크 α0.4)
                    FxPetCardPiece(sink, rig, "plane.H3", FxPetCard_pet_plane_H3, loop: false, filled: false, tone: 3, strokeMult: 0.75f, noStroke: false, lineAlpha: 0.42f, underBack: 3);   // 하이라이트
                    return true;
                case AppearanceShapeBuilder.PetMini:   // 리틀스틱메이트 — 조각 5
                    FxPetCardPiece(sink, rig, "mini.CB0", FxPetCard_pet_mini_CB0, loop: true, filled: true, tone: 0, strokeMult: 1f, noStroke: false, lineAlpha: 1f, underBack: 0);   // 머리(잉크 표식 — 카드 잉크 채움)  ※ 전문의 채움 역할은 INKF(카드 잉크). 역할표에 그 칸이 없어 재질색 M(잉크 톤)으로 굽는다
                    FxPetCardPiece(sink, rig, "mini.S1", FxPetCard_pet_mini_S1, loop: false, filled: false, tone: 4, strokeMult: 1.4f, noStroke: false, lineAlpha: 1f, underBack: 0);   // 몸통(잉크 ×1.4)
                    FxPetCardPiece(sink, rig, "mini.S2", FxPetCard_pet_mini_S2, loop: false, filled: false, tone: 4, strokeMult: 1.4f, noStroke: false, lineAlpha: 1f, underBack: 0);   // 팔
                    FxPetCardPiece(sink, rig, "mini.S3", FxPetCard_pet_mini_S3, loop: false, filled: false, tone: 4, strokeMult: 1.4f, noStroke: false, lineAlpha: 1f, underBack: 0);   // 다리
                    FxPetCardPiece(sink, rig, "mini.S4", FxPetCard_pet_mini_S4, loop: false, filled: false, tone: 4, strokeMult: 1.4f, noStroke: false, lineAlpha: 1f, underBack: 0);   // 다리
                    return true;
                case AppearanceShapeBuilder.PetCursor:   // 커서친구 — 조각 5
                    FxPetCardPiece(sink, rig, "cursor.B0head", FxPetCard_pet_cursor_B0head, loop: true, filled: true, tone: 0, strokeMult: 1f, noStroke: false, lineAlpha: 1f, underBack: 0);   // 화살표 머리(M Blue + 잉크) — 월드 CursorHead 와 같은 분할
                    FxPetCardPiece(sink, rig, "cursor.B1tail", FxPetCard_pet_cursor_B1tail, loop: true, filled: true, tone: 1, strokeMult: 1f, noStroke: false, lineAlpha: 1f, underBack: 0);   // 화살표 꼬리(M2 — 월드 CursorTail 과 같은 보조색)
                    FxPetCardPiece(sink, rig, "cursor.S1", FxPetCard_pet_cursor_S1, loop: false, filled: false, tone: 1, strokeMult: 1.2f, noStroke: false, lineAlpha: 1f, underBack: 0);   // 클릭 빛(독립선 M2 Paper ×1.2)
                    FxPetCardPiece(sink, rig, "cursor.S2", FxPetCard_pet_cursor_S2, loop: false, filled: false, tone: 1, strokeMult: 1.2f, noStroke: false, lineAlpha: 1f, underBack: 0);   // 클릭 빛
                    FxPetCardPiece(sink, rig, "cursor.H3", FxPetCard_pet_cursor_H3, loop: false, filled: false, tone: 3, strokeMult: 0.75f, noStroke: false, lineAlpha: 0.42f, underBack: 4);   // 하이라이트
                    return true;
                case AppearanceShapeBuilder.PetBalloon:   // 풍선 — 조각 4
                    FxPetCardPiece(sink, rig, "balloon.B0", FxPetCard_pet_balloon_B0, loop: true, filled: true, tone: 0, strokeMult: 1f, noStroke: false, lineAlpha: 1f, underBack: 0);   // 풍선(M Toy + 잉크)
                    FxPetCardPiece(sink, rig, "balloon.B1", FxPetCard_pet_balloon_B1, loop: true, filled: true, tone: 1, strokeMult: 1f, noStroke: false, lineAlpha: 1f, underBack: 0);   // 매듭(M2 Paper + 잉크)
                    FxPetCardPiece(sink, rig, "balloon.S2", FxPetCard_pet_balloon_S2, loop: false, filled: false, tone: 1, strokeMult: 1f, noStroke: false, lineAlpha: 1f, underBack: 0);   // 줄(독립선 M2)
                    FxPetCardPiece(sink, rig, "balloon.H3", FxPetCard_pet_balloon_H3, loop: false, filled: false, tone: 3, strokeMult: 0.75f, noStroke: false, lineAlpha: 0.42f, underBack: 3);   // 하이라이트
                    return true;
                case AppearanceShapeBuilder.PetSnail:   // 달팽이 — 조각 6
                    FxPetCardPiece(sink, rig, "snail.B0", FxPetCard_pet_snail_B0, loop: true, filled: true, tone: 1, strokeMult: 1f, noStroke: false, lineAlpha: 1f, underBack: 0);   // 발·머리(M2 Ivory + 잉크)
                    FxPetCardPiece(sink, rig, "snail.CB1", FxPetCard_pet_snail_CB1, loop: true, filled: true, tone: 0, strokeMult: 1f, noStroke: false, lineAlpha: 1f, underBack: 0);   // 껍데기(M Wool + 잉크)
                    FxPetCardPiece(sink, rig, "snail.CB2", FxPetCard_pet_snail_CB2, loop: true, filled: true, tone: 1, strokeMult: 1f, noStroke: true, lineAlpha: 1f, underBack: 1);   // 나선 심(M2, 윤곽 없음 — 색 경계)
                    FxPetCardPiece(sink, rig, "snail.S3", FxPetCard_pet_snail_S3, loop: false, filled: false, tone: 1, strokeMult: 1.1f, noStroke: false, lineAlpha: 1f, underBack: 0);   // 더듬이(독립선 M2)
                    FxPetCardPiece(sink, rig, "snail.S4", FxPetCard_pet_snail_S4, loop: false, filled: false, tone: 1, strokeMult: 1.1f, noStroke: false, lineAlpha: 1f, underBack: 0);   // 더듬이
                    FxPetCardPiece(sink, rig, "snail.H5", FxPetCard_pet_snail_H5, loop: false, filled: false, tone: 3, strokeMult: 0.75f, noStroke: false, lineAlpha: 0.42f, underBack: 4);   // 하이라이트
                    return true;
                default:
                    ShapeCoverageGuard.ReportMissingPetShape(item, "AccessoryShapeBuilder.FxPetCard(카드)");
                    return false;
            }
        }

        /// <summary>(다)군 카드 조각 하나. <see cref="HandoffPiece"/>와 같은 일을 하되
        /// <b>슬롯 박스도 몸 변형도 없다</b> — 좌표가 이미 전체 상자 프레이밍이라 그대로 놓는다.</summary>
        /// <param name="xyInR">머리 중심 원점 · R 배수 · y 위. 생성기가 64u 아이콘 좌표에서 되돌렸다.</param>
        private static void FxPetCardPiece(List<Shape> sink, in Rig rig, string name, float[] xyInR,
            bool loop, bool filled, byte tone, float strokeMult, bool noStroke, float lineAlpha, int underBack)
        {
            int n = xyInR.Length / 2;
            var pts = new Vector3[n];
            float r = rig.HeadRadius;
            float hc = rig.HeadCenterY;
            for (int i = 0; i < n; i++)
            {
                pts[i] = rig.F(xyInR[i * 2] * r, hc + xyInR[i * 2 + 1] * r);
            }
            sink.Add(new Shape(name, pts, loop, SortHead, -1, 0, tone, filled,
                (byte)AccessorySurface.Card, strokeMult, FxPetCardStrokeInR * strokeMult,
                noStroke, filled ? 1f : 0f, lineAlpha, underBack, 0, true));
        }

        /// <summary>(다)군 카드 조각의 명목 획(R 배수) = 인계본 아이콘 획 2.2f u ÷ 1 R 당 16.0f u.
        /// <para>이 값이 <b>화면 획을 정하지는 않는다</b> — 카드는 언제나
        /// <c>AccessoryCardIcon.Frame.StrokeFraction</c>(2.2/64) × 배수로 그린다. 여기 있는 이유는
        /// 두 가지다: (가) 0 보다 커야 <see cref="Shape.IsHandoff"/>가 참이 되어 계약 v2 색 문법
        /// (잉크 윤곽 + 재질 채움 + 흰 하이라이트)을 타고, (나) 그 값이 <b>임의의 표식이 아니라
        /// 같은 프레이밍에서 유도된 실제 폭</b>이어야 다음 사람이 숫자의 출처를 찾을 수 있다.
        /// 몸 표면에는 이 조각이 아예 가지 않으므로(카드 전용) 몸 획 계산에는 쓰이지 않는다.</para></summary>
        internal const float FxPetCardStrokeInR = 2.2f / 16.0f;

        private static readonly float[] FxPetCard_fx_none_CB0 = {
            1.00000f, -0.12500f, 0.96563f, -0.38375f, 0.86625f, -0.62500f, 0.70688f, -0.83188f, 0.50000f, -0.99125f,
            0.25875f, -1.09063f, 0.00000f, -1.12500f, -0.25875f, -1.09063f, -0.50000f, -0.99125f, -0.70687f, -0.83188f,
            -0.86625f, -0.62500f, -0.96562f, -0.38375f, -1.00000f, -0.12500f, -0.96562f, 0.13375f, -0.86625f, 0.37500f,
            -0.70687f, 0.58187f, -0.50000f, 0.74125f, -0.25875f, 0.84062f, 0.00000f, 0.87500f, 0.25875f, 0.84062f,
            0.50000f, 0.74125f, 0.70688f, 0.58187f, 0.86625f, 0.37500f, 0.96563f, 0.13375f
        };

        private static readonly float[] FxPetCard_fx_none_S1 = {
            -0.65625f, -0.78125f, 0.65625f, 0.53125f
        };

        private static readonly float[] FxPetCard_fx_footprint_B0 = {
            -0.50000f, 1.25000f, -0.40813f, 1.27812f, -0.32000f, 1.29875f, -0.23625f, 1.31312f, -0.15625f, 1.32000f,
            -0.08000f, 1.32063f, -0.00750f, 1.31438f, 0.06062f, 1.30125f, 0.12500f, 1.28125f, 0.18562f, 1.25438f,
            0.24250f, 1.22063f, 0.29500f, 1.18000f, 0.34375f, 1.13250f, 0.38875f, 1.07875f, 0.43000f, 1.01750f,
            0.46687f, 0.95000f, 0.50000f, 0.87500f, 0.52125f, 0.79750f, 0.53812f, 0.72063f, 0.55063f, 0.64500f,
            0.55875f, 0.57000f, 0.56250f, 0.49687f, 0.56125f, 0.42375f, 0.55625f, 0.35187f, 0.54688f, 0.28125f,
            0.53313f, 0.21125f, 0.51437f, 0.14250f, 0.49187f, 0.07500f, 0.46500f, 0.00750f, 0.43312f, -0.05812f,
            0.39750f, -0.12312f, 0.35688f, -0.18688f, 0.31250f, -0.25000f, 0.28187f, -0.29688f, 0.25188f, -0.34375f,
            0.22313f, -0.39062f, 0.19500f, -0.43750f, 0.16875f, -0.48438f, 0.14250f, -0.53125f, 0.11750f, -0.57812f,
            0.09375f, -0.62500f, 0.07063f, -0.67188f, 0.04875f, -0.71875f, 0.02813f, -0.76562f, 0.00750f, -0.81250f,
            -0.01125f, -0.85938f, -0.02937f, -0.90625f, -0.04625f, -0.95312f, -0.06250f, -1.00000f, -0.08688f, -1.07500f,
            -0.11437f, -1.14438f, -0.14375f, -1.20812f, -0.17562f, -1.26562f, -0.21000f, -1.31750f, -0.24687f, -1.36313f,
            -0.28625f, -1.40313f, -0.32812f, -1.43750f, -0.37250f, -1.46563f, -0.41875f, -1.48813f, -0.46812f, -1.50500f,
            -0.51937f, -1.51562f, -0.57375f, -1.52062f, -0.63000f, -1.51938f, -0.68875f, -1.51250f, -0.75000f, -1.50000f,
            -0.80187f, -1.46750f, -0.84875f, -1.43187f, -0.89000f, -1.39312f, -0.92562f, -1.35125f, -0.95625f, -1.30687f,
            -0.98125f, -1.26000f, -1.00125f, -1.20938f, -1.01562f, -1.15625f, -1.02438f, -1.10000f, -1.02812f, -1.04125f,
            -1.02687f, -0.97875f, -1.01938f, -0.91375f, -1.00687f, -0.84625f, -0.98937f, -0.77562f, -0.96625f, -0.70187f,
            -0.93750f, -0.62500f, -0.90750f, -0.56188f, -0.88000f, -0.49812f, -0.85500f, -0.43312f, -0.83187f, -0.36750f,
            -0.81187f, -0.30000f, -0.79375f, -0.23250f, -0.77875f, -0.16375f, -0.76562f, -0.09375f, -0.75500f, -0.02313f,
            -0.74687f, 0.04875f, -0.74125f, 0.12187f, -0.73812f, 0.19500f, -0.73750f, 0.27000f, -0.73937f, 0.34563f,
            -0.74313f, 0.42250f, -0.75000f, 0.50000f, -0.75625f, 0.56875f, -0.76000f, 0.63500f, -0.76000f, 0.69750f,
            -0.75750f, 0.75750f, -0.75250f, 0.81500f, -0.74438f, 0.86938f, -0.73313f, 0.92063f, -0.71875f, 0.96875f,
            -0.70188f, 1.01438f, -0.68188f, 1.05688f, -0.65875f, 1.09625f, -0.63250f, 1.13250f, -0.60375f, 1.16625f,
            -0.57250f, 1.19750f, -0.53750f, 1.22500f
        };

        private static readonly float[] FxPetCard_fx_footprint_CB1 = {
            0.90625f, 1.43750f, 0.89875f, 1.38062f, 0.87688f, 1.32812f, 0.84187f, 1.28313f, 0.79688f, 1.24812f,
            0.74437f, 1.22625f, 0.68750f, 1.21875f, 0.63063f, 1.22625f, 0.57812f, 1.24812f, 0.53313f, 1.28313f,
            0.49812f, 1.32812f, 0.47625f, 1.38062f, 0.46875f, 1.43750f, 0.47625f, 1.49438f, 0.49812f, 1.54688f,
            0.53313f, 1.59187f, 0.57812f, 1.62688f, 0.63063f, 1.64875f, 0.68750f, 1.65625f, 0.74437f, 1.64875f,
            0.79688f, 1.62688f, 0.84187f, 1.59187f, 0.87688f, 1.54688f, 0.89875f, 1.49438f
        };

        private static readonly float[] FxPetCard_fx_footprint_S2 = {
            -0.81250f, -0.37500f, -0.74250f, -0.35312f, -0.67312f, -0.33375f, -0.60375f, -0.31813f, -0.53500f, -0.30500f,
            -0.46687f, -0.29438f, -0.39938f, -0.28688f, -0.33250f, -0.28250f, -0.26562f, -0.28125f, -0.19938f, -0.28250f,
            -0.13375f, -0.28688f, -0.06875f, -0.29438f, -0.00375f, -0.30500f, 0.06000f, -0.31813f, 0.12375f, -0.33375f,
            0.18750f, -0.35312f, 0.25000f, -0.37500f
        };

        private static readonly float[] FxPetCard_fx_footprint_H3 = {
            -0.50000f, 0.62500f, -0.49125f, 0.66312f, -0.48125f, 0.70000f, -0.47000f, 0.73562f, -0.45687f, 0.76937f,
            -0.44250f, 0.80187f, -0.42687f, 0.83312f, -0.40938f, 0.86250f, -0.39062f, 0.89062f, -0.37062f, 0.91750f,
            -0.34875f, 0.94250f, -0.32563f, 0.96625f, -0.30062f, 0.98813f, -0.27438f, 1.00875f, -0.24687f, 1.02812f,
            -0.21812f, 1.04625f, -0.18750f, 1.06250f
        };

        private static readonly float[] FxPetCard_fx_sparkle_B0 = {
            -0.12500f, 1.50000f, 0.26567f, 0.26568f, 1.50000f, -0.12500f, 0.26567f, -0.51567f, -0.12500f, -1.75000f,
            -0.51568f, -0.51567f, -1.75000f, -0.12500f, -0.51568f, 0.26568f
        };

        private static readonly float[] FxPetCard_fx_sparkle_CF1 = {
            1.25000f, 1.62500f, 1.38523f, 1.19773f, 1.81250f, 1.06250f, 1.38523f, 0.92727f, 1.25000f, 0.50000f,
            1.11477f, 0.92727f, 0.68750f, 1.06250f, 1.11477f, 1.19773f
        };

        private static readonly float[] FxPetCard_fx_sparkle_S2 = {
            -1.50000f, -1.37500f, -1.18750f, -1.37500f
        };

        private static readonly float[] FxPetCard_fx_sparkle_H3 = {
            -0.56250f, 0.50000f, -0.54625f, 0.53812f, -0.52937f, 0.57500f, -0.51125f, 0.61062f, -0.49250f, 0.64437f,
            -0.47188f, 0.67687f, -0.45125f, 0.70812f, -0.42938f, 0.73750f, -0.40625f, 0.76562f, -0.38250f, 0.79250f,
            -0.35750f, 0.81750f, -0.33125f, 0.84125f, -0.30500f, 0.86312f, -0.27687f, 0.88375f, -0.24812f, 0.90312f,
            -0.21812f, 0.92125f, -0.18750f, 0.93750f
        };

        private static readonly float[] FxPetCard_fx_dust_B0 = {
            -1.37500f, -0.87500f, -1.41688f, -0.78375f, -1.44937f, -0.69750f, -1.47188f, -0.61563f, -1.48438f, -0.53875f,
            -1.48750f, -0.46750f, -1.48062f, -0.40062f, -1.46375f, -0.33812f, -1.43750f, -0.28125f, -1.40125f, -0.22875f,
            -1.35562f, -0.18187f, -1.30000f, -0.13937f, -1.23438f, -0.10125f, -1.15938f, -0.06875f, -1.07437f, -0.04125f,
            -0.97938f, -0.01812f, -0.87500f, 0.00000f, -0.85625f, 0.10500f, -0.83187f, 0.20125f, -0.80187f, 0.28875f,
            -0.76562f, 0.36750f, -0.72375f, 0.43687f, -0.67562f, 0.49812f, -0.62187f, 0.55000f, -0.56250f, 0.59375f,
            -0.49687f, 0.62813f, -0.42562f, 0.65437f, -0.34875f, 0.67125f, -0.26562f, 0.68000f, -0.17687f, 0.67938f,
            -0.08187f, 0.67000f, 0.01875f, 0.65187f, 0.12500f, 0.62500f, 0.23188f, 0.68188f, 0.33375f, 0.72625f,
            0.43125f, 0.76000f, 0.52375f, 0.78125f, 0.61063f, 0.79125f, 0.69313f, 0.78875f, 0.77125f, 0.77563f,
            0.84375f, 0.75000f, 0.91188f, 0.71313f, 0.97438f, 0.66375f, 1.03250f, 0.60375f, 1.08625f, 0.53125f,
            1.13437f, 0.44750f, 1.17750f, 0.35125f, 1.21625f, 0.24438f, 1.25000f, 0.12500f, 1.32500f, 0.10625f,
            1.39250f, 0.08187f, 1.45375f, 0.05187f, 1.50750f, 0.01562f, 1.55500f, -0.02625f, 1.59563f, -0.07438f,
            1.62938f, -0.12812f, 1.65625f, -0.18750f, 1.67625f, -0.25312f, 1.68938f, -0.32437f, 1.69563f, -0.40125f,
            1.69500f, -0.48438f, 1.68812f, -0.57313f, 1.67375f, -0.66812f, 1.65313f, -0.76875f, 1.62500f, -0.87500f
        };

        private static readonly float[] FxPetCard_fx_dust_CB1 = {
            -0.90625f, -1.37500f, -0.91562f, -1.44750f, -0.94375f, -1.51562f, -0.98875f, -1.57375f, -1.04688f, -1.61875f,
            -1.11500f, -1.64688f, -1.18750f, -1.65625f, -1.26000f, -1.64688f, -1.32812f, -1.61875f, -1.38625f, -1.57375f,
            -1.43125f, -1.51562f, -1.45938f, -1.44750f, -1.46875f, -1.37500f, -1.45938f, -1.30250f, -1.43125f, -1.23438f,
            -1.38625f, -1.17625f, -1.32812f, -1.13125f, -1.26000f, -1.10312f, -1.18750f, -1.09375f, -1.11500f, -1.10312f,
            -1.04688f, -1.13125f, -0.98875f, -1.17625f, -0.94375f, -1.23438f, -0.91562f, -1.30250f
        };

        private static readonly float[] FxPetCard_fx_dust_CB2 = {
            1.53125f, -1.43750f, 1.52375f, -1.49437f, 1.50188f, -1.54688f, 1.46687f, -1.59187f, 1.42188f, -1.62688f,
            1.36937f, -1.64875f, 1.31250f, -1.65625f, 1.25563f, -1.64875f, 1.20312f, -1.62688f, 1.15813f, -1.59187f,
            1.12312f, -1.54688f, 1.10125f, -1.49437f, 1.09375f, -1.43750f, 1.10125f, -1.38063f, 1.12312f, -1.32812f,
            1.15813f, -1.28313f, 1.20312f, -1.24812f, 1.25563f, -1.22625f, 1.31250f, -1.21875f, 1.36937f, -1.22625f,
            1.42188f, -1.24812f, 1.46687f, -1.28313f, 1.50188f, -1.32812f, 1.52375f, -1.38063f
        };

        private static readonly float[] FxPetCard_fx_dust_H3 = {
            -0.87500f, -0.37500f, -0.85813f, -0.32875f, -0.84000f, -0.28437f, -0.81937f, -0.24125f, -0.79688f, -0.19937f,
            -0.77250f, -0.15875f, -0.74625f, -0.12000f, -0.71750f, -0.08250f, -0.68750f, -0.04688f, -0.65500f, -0.01250f,
            -0.62125f, 0.02062f, -0.58500f, 0.05187f, -0.54688f, 0.08187f, -0.50687f, 0.11062f, -0.46500f, 0.13750f,
            -0.42063f, 0.16312f, -0.37500f, 0.18750f
        };

        private static readonly float[] FxPetCard_fx_bubble_CB0 = {
            1.18750f, 0.06250f, 1.14250f, -0.27750f, 1.01187f, -0.59375f, 0.80313f, -0.86563f, 0.53125f, -1.07437f,
            0.21500f, -1.20500f, -0.12500f, -1.25000f, -0.46500f, -1.20500f, -0.78125f, -1.07437f, -1.05313f, -0.86563f,
            -1.26187f, -0.59375f, -1.39250f, -0.27750f, -1.43750f, 0.06250f, -1.39250f, 0.40250f, -1.26187f, 0.71875f,
            -1.05313f, 0.99062f, -0.78125f, 1.19937f, -0.46500f, 1.33000f, -0.12500f, 1.37500f, 0.21500f, 1.33000f,
            0.53125f, 1.19937f, 0.80313f, 0.99062f, 1.01187f, 0.71875f, 1.14250f, 0.40250f
        };

        private static readonly float[] FxPetCard_fx_bubble_CB1 = {
            1.68750f, -1.25000f, 1.67500f, -1.34687f, 1.63750f, -1.43750f, 1.57750f, -1.51500f, 1.50000f, -1.57500f,
            1.40937f, -1.61250f, 1.31250f, -1.62500f, 1.21563f, -1.61250f, 1.12500f, -1.57500f, 1.04750f, -1.51500f,
            0.98750f, -1.43750f, 0.95000f, -1.34687f, 0.93750f, -1.25000f, 0.95000f, -1.15313f, 0.98750f, -1.06250f,
            1.04750f, -0.98500f, 1.12500f, -0.92500f, 1.21563f, -0.88750f, 1.31250f, -0.87500f, 1.40937f, -0.88750f,
            1.50000f, -0.92500f, 1.57750f, -0.98500f, 1.63750f, -1.06250f, 1.67500f, -1.15313f
        };

        private static readonly float[] FxPetCard_fx_bubble_CB2 = {
            -1.06250f, -1.37500f, -1.07125f, -1.44000f, -1.09625f, -1.50000f, -1.13563f, -1.55187f, -1.18750f, -1.59125f,
            -1.24750f, -1.61625f, -1.31250f, -1.62500f, -1.37750f, -1.61625f, -1.43750f, -1.59125f, -1.48937f, -1.55187f,
            -1.52875f, -1.50000f, -1.55375f, -1.44000f, -1.56250f, -1.37500f, -1.55375f, -1.31000f, -1.52875f, -1.25000f,
            -1.48937f, -1.19813f, -1.43750f, -1.15875f, -1.37750f, -1.13375f, -1.31250f, -1.12500f, -1.24750f, -1.13375f,
            -1.18750f, -1.15875f, -1.13563f, -1.19813f, -1.09625f, -1.25000f, -1.07125f, -1.31000f
        };

        private static readonly float[] FxPetCard_fx_bubble_H3 = {
            -1.00000f, 0.25000f, -0.99000f, 0.33438f, -0.97562f, 0.41500f, -0.95687f, 0.49250f, -0.93375f, 0.56625f,
            -0.90625f, 0.63688f, -0.87375f, 0.70437f, -0.83750f, 0.76812f, -0.79688f, 0.82812f, -0.75188f, 0.88500f,
            -0.70188f, 0.93875f, -0.64813f, 0.98875f, -0.59000f, 1.03500f, -0.52687f, 1.07812f, -0.46000f, 1.11813f,
            -0.38813f, 1.15437f, -0.31250f, 1.18750f
        };

        private static readonly float[] FxPetCard_fx_leaf_B0 = {
            -1.50000f, -1.50000f, -1.49500f, -1.28437f, -1.48062f, -1.07625f, -1.45625f, -0.87438f, -1.42188f, -0.68000f,
            -1.37813f, -0.49187f, -1.32437f, -0.31062f, -1.26063f, -0.13625f, -1.18750f, 0.03125f, -1.10438f, 0.19188f,
            -1.01187f, 0.34563f, -0.90938f, 0.49250f, -0.79688f, 0.63250f, -0.67500f, 0.76625f, -0.54313f, 0.89250f,
            -0.40125f, 1.01250f, -0.25000f, 1.12500f, -0.08125f, 1.20000f, 0.08188f, 1.26750f, 0.23937f, 1.32875f,
            0.39062f, 1.38250f, 0.53625f, 1.43000f, 0.67563f, 1.47063f, 0.80938f, 1.50438f, 0.93750f, 1.53125f,
            1.05938f, 1.55125f, 1.17563f, 1.56438f, 1.28625f, 1.57062f, 1.39062f, 1.57000f, 1.48937f, 1.56312f,
            1.58188f, 1.54875f, 1.66875f, 1.52812f, 1.75000f, 1.50000f, 1.72875f, 1.25500f, 1.69750f, 1.01938f,
            1.65500f, 0.79375f, 1.60125f, 0.57812f, 1.53750f, 0.37187f, 1.46312f, 0.17562f, 1.37750f, -0.01063f,
            1.28125f, -0.18750f, 1.17437f, -0.35438f, 1.05687f, -0.51187f, 0.92813f, -0.65937f, 0.78875f, -0.79688f,
            0.63937f, -0.92500f, 0.47875f, -1.04312f, 0.30687f, -1.15125f, 0.12500f, -1.25000f, 0.01625f, -1.29500f,
            -0.09187f, -1.33625f, -0.19875f, -1.37312f, -0.30500f, -1.40625f, -0.40938f, -1.43562f, -0.51375f, -1.46125f,
            -0.61688f, -1.48250f, -0.71875f, -1.50000f, -0.82000f, -1.51375f, -0.92000f, -1.52375f, -1.01875f, -1.52937f,
            -1.11750f, -1.53125f, -1.21437f, -1.52937f, -1.31062f, -1.52375f, -1.40563f, -1.51375f
        };

        private static readonly float[] FxPetCard_fx_leaf_S1 = {
            -1.25000f, -1.31250f, -1.10750f, -1.17875f, -0.96125f, -1.04188f, -0.81062f, -0.90313f, -0.65625f, -0.76187f,
            -0.49812f, -0.61813f, -0.33625f, -0.47187f, -0.17000f, -0.32313f, 0.00000f, -0.17188f, 0.17375f, -0.01812f,
            0.35125f, 0.13750f, 0.53313f, 0.29625f, 0.71875f, 0.45687f, 0.90813f, 0.62062f, 1.10125f, 0.78625f,
            1.29875f, 0.95437f, 1.50000f, 1.12500f
        };

        private static readonly float[] FxPetCard_fx_leaf_S2 = {
            -1.50000f, -1.50000f, -1.81250f, -1.93750f
        };

        private static readonly float[] FxPetCard_fx_leaf_H3 = {
            -1.00000f, -0.75000f, -0.97562f, -0.67313f, -0.94813f, -0.59750f, -0.91875f, -0.52438f, -0.88688f, -0.45312f,
            -0.85250f, -0.38375f, -0.81563f, -0.31625f, -0.77625f, -0.25125f, -0.73438f, -0.18750f, -0.69000f, -0.12625f,
            -0.64375f, -0.06625f, -0.59438f, -0.00875f, -0.54313f, 0.04688f, -0.48875f, 0.10062f, -0.43250f, 0.15250f,
            -0.37375f, 0.20188f, -0.31250f, 0.25000f
        };

        private static readonly float[] FxPetCard_pet_ball_CB0 = {
            1.43750f, -0.12500f, 1.38875f, -0.49688f, 1.24500f, -0.84375f, 1.01625f, -1.14125f, 0.71875f, -1.37000f,
            0.37188f, -1.51375f, 0.00000f, -1.56250f, -0.37187f, -1.51375f, -0.71875f, -1.37000f, -1.01625f, -1.14125f,
            -1.24500f, -0.84375f, -1.38875f, -0.49688f, -1.43750f, -0.12500f, -1.38875f, 0.24687f, -1.24500f, 0.59375f,
            -1.01625f, 0.89125f, -0.71875f, 1.12000f, -0.37187f, 1.26375f, 0.00000f, 1.31250f, 0.37188f, 1.26375f,
            0.71875f, 1.12000f, 1.01625f, 0.89125f, 1.24500f, 0.59375f, 1.38875f, 0.24687f
        };

        private static readonly float[] FxPetCard_pet_ball_S1 = {
            0.00000f, 1.31250f, 0.11000f, 1.13250f, 0.20500f, 0.95312f, 0.28563f, 0.77375f, 0.35125f, 0.59375f,
            0.40313f, 0.41375f, 0.43938f, 0.23438f, 0.46125f, 0.05500f, 0.46875f, -0.12500f, 0.46125f, -0.30500f,
            0.43938f, -0.48438f, 0.40313f, -0.66375f, 0.35125f, -0.84375f, 0.28563f, -1.02375f, 0.20500f, -1.20312f,
            0.11000f, -1.38250f, 0.00000f, -1.56250f
        };

        private static readonly float[] FxPetCard_pet_ball_S2 = {
            0.00000f, 1.31250f, -0.11000f, 1.13250f, -0.20500f, 0.95312f, -0.28563f, 0.77375f, -0.35125f, 0.59375f,
            -0.40312f, 0.41375f, -0.43938f, 0.23438f, -0.46125f, 0.05500f, -0.46875f, -0.12500f, -0.46125f, -0.30500f,
            -0.43938f, -0.48438f, -0.40312f, -0.66375f, -0.35125f, -0.84375f, -0.28563f, -1.02375f, -0.20500f, -1.20312f,
            -0.11000f, -1.38250f, 0.00000f, -1.56250f
        };

        private static readonly float[] FxPetCard_pet_ball_H3 = {
            -0.93750f, 0.37500f, -0.92063f, 0.43625f, -0.90125f, 0.49500f, -0.87938f, 0.55125f, -0.85563f, 0.60563f,
            -0.82875f, 0.65688f, -0.80000f, 0.70625f, -0.76812f, 0.75250f, -0.73438f, 0.79688f, -0.69813f, 0.83875f,
            -0.65938f, 0.87813f, -0.61813f, 0.91500f, -0.57438f, 0.94937f, -0.52812f, 0.98125f, -0.47938f, 1.01063f,
            -0.42875f, 1.03812f, -0.37500f, 1.06250f
        };

        private static readonly float[] FxPetCard_pet_plane_B0 = {
            1.75000f, 1.25000f, -1.75000f, 0.12500f, -0.50000f, -0.25000f
        };

        private static readonly float[] FxPetCard_pet_plane_B1 = {
            1.75000f, 1.25000f, -0.50000f, -0.25000f, 0.12500f, -0.50000f, -0.12500f, -1.62500f
        };

        private static readonly float[] FxPetCard_pet_plane_S2 = {
            1.75000f, 1.25000f, -0.50000f, -0.25000f
        };

        private static readonly float[] FxPetCard_pet_plane_H3 = {
            -1.00000f, 0.25000f, -0.95188f, 0.28062f, -0.90250f, 0.31062f, -0.85062f, 0.33937f, -0.79688f, 0.36750f,
            -0.74125f, 0.39375f, -0.68375f, 0.42000f, -0.62375f, 0.44500f, -0.56250f, 0.46875f, -0.49875f, 0.49188f,
            -0.43375f, 0.51375f, -0.36625f, 0.53438f, -0.29688f, 0.55500f, -0.22562f, 0.57375f, -0.15250f, 0.59187f,
            -0.07688f, 0.60875f, 0.00000f, 0.62500f
        };

        private static readonly float[] FxPetCard_pet_mini_CB0 = {
            0.56250f, 1.06250f, 0.54312f, 0.91687f, 0.48687f, 0.78125f, 0.39750f, 0.66500f, 0.28125f, 0.57563f,
            0.14562f, 0.51937f, 0.00000f, 0.50000f, -0.14562f, 0.51937f, -0.28125f, 0.57563f, -0.39750f, 0.66500f,
            -0.48687f, 0.78125f, -0.54313f, 0.91687f, -0.56250f, 1.06250f, -0.54313f, 1.20812f, -0.48687f, 1.34375f,
            -0.39750f, 1.46000f, -0.28125f, 1.54937f, -0.14562f, 1.60563f, 0.00000f, 1.62500f, 0.14562f, 1.60563f,
            0.28125f, 1.54937f, 0.39750f, 1.46000f, 0.48687f, 1.34375f, 0.54312f, 1.20812f
        };

        private static readonly float[] FxPetCard_pet_mini_S1 = {
            0.00000f, 0.50000f, 0.00000f, -0.62500f
        };

        private static readonly float[] FxPetCard_pet_mini_S2 = {
            -0.93750f, -0.43750f, 0.00000f, 0.12500f, 0.93750f, -0.43750f
        };

        private static readonly float[] FxPetCard_pet_mini_S3 = {
            0.00000f, -0.62500f, -0.68750f, -1.81250f
        };

        private static readonly float[] FxPetCard_pet_mini_S4 = {
            0.00000f, -0.62500f, 0.68750f, -1.81250f
        };

        private static readonly float[] FxPetCard_pet_cursor_B0head = {
            -1.00000f, 1.37500f, -1.00000f, -1.00000f, -0.43750f, -0.50000f, 0.00000f, -0.37500f, 0.75000f, -0.37500f
        };

        private static readonly float[] FxPetCard_pet_cursor_B1tail = {
            -0.43750f, -0.50000f, 0.00000f, -1.50000f, 0.43750f, -1.31250f, 0.00000f, -0.37500f
        };

        private static readonly float[] FxPetCard_pet_cursor_S1 = {
            -1.25000f, 1.56250f, -1.62500f, 1.81250f
        };

        private static readonly float[] FxPetCard_pet_cursor_S2 = {
            -1.31250f, 1.06250f, -1.75000f, 1.06250f
        };

        private static readonly float[] FxPetCard_pet_cursor_H3 = {
            -0.81250f, 1.00000f, -0.80812f, 0.95312f, -0.80375f, 0.90625f, -0.79875f, 0.85938f, -0.79313f, 0.81250f,
            -0.78687f, 0.76562f, -0.78000f, 0.71875f, -0.77313f, 0.67188f, -0.76562f, 0.62500f, -0.75750f, 0.57812f,
            -0.74875f, 0.53125f, -0.74000f, 0.48438f, -0.73063f, 0.43750f, -0.72063f, 0.39062f, -0.71000f, 0.34375f,
            -0.69875f, 0.29688f, -0.68750f, 0.25000f
        };

        private static readonly float[] FxPetCard_pet_balloon_B0 = {
            0.00000f, 1.62500f, 0.12125f, 1.62062f, 0.23438f, 1.60750f, 0.34000f, 1.58563f, 0.43750f, 1.55500f,
            0.52750f, 1.51500f, 0.60938f, 1.46687f, 0.68375f, 1.40938f, 0.75000f, 1.34375f, 0.80875f, 1.26875f,
            0.85938f, 1.18562f, 0.90250f, 1.09313f, 0.93750f, 0.99250f, 0.96500f, 0.88250f, 0.98438f, 0.76375f,
            0.99625f, 0.63625f, 1.00000f, 0.50000f, 0.99625f, 0.37688f, 0.98438f, 0.25750f, 0.96500f, 0.14250f,
            0.93750f, 0.03125f, 0.90250f, -0.07625f, 0.85938f, -0.18000f, 0.80875f, -0.27937f, 0.75000f, -0.37500f,
            0.68375f, -0.46687f, 0.60938f, -0.55500f, 0.52750f, -0.63875f, 0.43750f, -0.71875f, 0.34000f, -0.79500f,
            0.23438f, -0.86750f, 0.12125f, -0.93562f, 0.00000f, -1.00000f, -0.12125f, -0.93562f, -0.23438f, -0.86750f,
            -0.34000f, -0.79500f, -0.43750f, -0.71875f, -0.52750f, -0.63875f, -0.60938f, -0.55500f, -0.68375f, -0.46687f,
            -0.75000f, -0.37500f, -0.80875f, -0.27937f, -0.85938f, -0.18000f, -0.90250f, -0.07625f, -0.93750f, 0.03125f,
            -0.96500f, 0.14250f, -0.98438f, 0.25750f, -0.99625f, 0.37688f, -1.00000f, 0.50000f, -0.99625f, 0.63625f,
            -0.98438f, 0.76375f, -0.96500f, 0.88250f, -0.93750f, 0.99250f, -0.90250f, 1.09313f, -0.85938f, 1.18562f,
            -0.80875f, 1.26875f, -0.75000f, 1.34375f, -0.68375f, 1.40938f, -0.60938f, 1.46687f, -0.52750f, 1.51500f,
            -0.43750f, 1.55500f, -0.34000f, 1.58563f, -0.23438f, 1.60750f, -0.12125f, 1.62062f
        };

        private static readonly float[] FxPetCard_pet_balloon_B1 = {
            -0.28125f, -0.93750f, 0.28125f, -0.93750f, 0.00000f, -1.31250f
        };

        private static readonly float[] FxPetCard_pet_balloon_S2 = {
            0.00000f, -1.31250f, -0.04375f, -1.34375f, -0.08187f, -1.37500f, -0.11437f, -1.40625f, -0.14062f, -1.43750f,
            -0.16125f, -1.46875f, -0.17562f, -1.50000f, -0.18437f, -1.53125f, -0.18750f, -1.56250f, -0.18437f, -1.59375f,
            -0.17562f, -1.62500f, -0.16125f, -1.65625f, -0.14062f, -1.68750f, -0.11437f, -1.71875f, -0.08187f, -1.75000f,
            -0.04375f, -1.78125f, 0.00000f, -1.81250f, 0.04375f, -1.83562f, 0.08188f, -1.85812f, 0.11437f, -1.88063f,
            0.14062f, -1.90250f, 0.16125f, -1.92375f, 0.17563f, -1.94437f, 0.18438f, -1.96437f, 0.18750f, -1.98438f,
            0.18438f, -2.00375f, 0.17563f, -2.02250f, 0.16125f, -2.04062f, 0.14062f, -2.05875f, 0.11437f, -2.07563f,
            0.08188f, -2.09250f, 0.04375f, -2.10938f, 0.00000f, -2.12500f
        };

        private static readonly float[] FxPetCard_pet_balloon_H3 = {
            -0.62500f, 0.75000f, -0.61625f, 0.81125f, -0.60438f, 0.86938f, -0.59062f, 0.92437f, -0.57438f, 0.97625f,
            -0.55563f, 1.02563f, -0.53438f, 1.07250f, -0.51063f, 1.11563f, -0.48438f, 1.15625f, -0.45562f, 1.19375f,
            -0.42500f, 1.22875f, -0.39125f, 1.26000f, -0.35563f, 1.28875f, -0.31688f, 1.31500f, -0.27625f, 1.33813f,
            -0.23313f, 1.35813f, -0.18750f, 1.37500f
        };

        private static readonly float[] FxPetCard_pet_snail_B0 = {
            -1.50000f, -1.37500f, -1.53000f, -1.37375f, -1.55875f, -1.37000f, -1.58500f, -1.36375f, -1.60938f, -1.35562f,
            -1.63187f, -1.34437f, -1.65250f, -1.33125f, -1.67063f, -1.31500f, -1.68750f, -1.29688f, -1.70188f, -1.27625f,
            -1.71500f, -1.25312f, -1.72562f, -1.22750f, -1.73438f, -1.19937f, -1.74125f, -1.16875f, -1.74625f, -1.13563f,
            -1.74875f, -1.10062f, -1.75000f, -1.06250f, -1.74875f, -1.02438f, -1.74438f, -0.98937f, -1.73687f, -0.95625f,
            -1.72625f, -0.92563f, -1.71313f, -0.89750f, -1.69750f, -0.87188f, -1.67813f, -0.84875f, -1.65625f, -0.82812f,
            -1.63125f, -0.81000f, -1.60375f, -0.79375f, -1.57250f, -0.78063f, -1.53875f, -0.76938f, -1.50250f, -0.76125f,
            -1.46313f, -0.75500f, -1.42063f, -0.75125f, -1.37500f, -0.75000f, 1.00000f, -0.75000f, 1.06125f, -0.74812f,
            1.11937f, -0.74250f, 1.17437f, -0.73250f, 1.22625f, -0.71875f, 1.27562f, -0.70125f, 1.32250f, -0.68000f,
            1.36563f, -0.65437f, 1.40625f, -0.62500f, 1.44375f, -0.59187f, 1.47875f, -0.55500f, 1.51000f, -0.51375f,
            1.53875f, -0.46875f, 1.56500f, -0.42000f, 1.58812f, -0.36750f, 1.60812f, -0.31062f, 1.62500f, -0.25000f,
            1.62500f, -0.62500f, 1.62250f, -0.71563f, 1.61500f, -0.80063f, 1.60312f, -0.88000f, 1.58625f, -0.95312f,
            1.56375f, -1.02062f, 1.53688f, -1.08188f, 1.50563f, -1.13750f, 1.46875f, -1.18750f, 1.42750f, -1.23125f,
            1.38063f, -1.26938f, 1.32938f, -1.30187f, 1.27375f, -1.32812f, 1.21250f, -1.34875f, 1.14625f, -1.36313f,
            1.07563f, -1.37188f, 1.00000f, -1.37500f
        };

        private static readonly float[] FxPetCard_pet_snail_CB1 = {
            0.87500f, 0.18750f, 0.83875f, -0.08750f, 0.73250f, -0.34375f, 0.56375f, -0.56375f, 0.34375f, -0.73250f,
            0.08750f, -0.83875f, -0.18750f, -0.87500f, -0.46250f, -0.83875f, -0.71875f, -0.73250f, -0.93875f, -0.56375f,
            -1.10750f, -0.34375f, -1.21375f, -0.08750f, -1.25000f, 0.18750f, -1.21375f, 0.46250f, -1.10750f, 0.71875f,
            -0.93875f, 0.93875f, -0.71875f, 1.10750f, -0.46250f, 1.21375f, -0.18750f, 1.25000f, 0.08750f, 1.21375f,
            0.34375f, 1.10750f, 0.56375f, 0.93875f, 0.73250f, 0.71875f, 0.83875f, 0.46250f
        };

        private static readonly float[] FxPetCard_pet_snail_CB2 = {
            0.21875f, 0.18750f, 0.20500f, 0.08250f, 0.16438f, -0.01562f, 0.10000f, -0.10000f, 0.01562f, -0.16438f,
            -0.08250f, -0.20500f, -0.18750f, -0.21875f, -0.29250f, -0.20500f, -0.39062f, -0.16438f, -0.47500f, -0.10000f,
            -0.53937f, -0.01562f, -0.58000f, 0.08250f, -0.59375f, 0.18750f, -0.58000f, 0.29250f, -0.53937f, 0.39062f,
            -0.47500f, 0.47500f, -0.39062f, 0.53937f, -0.29250f, 0.58000f, -0.18750f, 0.59375f, -0.08250f, 0.58000f,
            0.01562f, 0.53937f, 0.10000f, 0.47500f, 0.16438f, 0.39062f, 0.20500f, 0.29250f
        };

        private static readonly float[] FxPetCard_pet_snail_S3 = {
            1.37500f, -0.37500f, 1.62500f, 0.25000f
        };

        private static readonly float[] FxPetCard_pet_snail_S4 = {
            1.12500f, -0.31250f, 1.06250f, 0.25000f
        };

        private static readonly float[] FxPetCard_pet_snail_H5 = {
            -0.93750f, 0.25000f, -0.92875f, 0.31125f, -0.91688f, 0.37000f, -0.90312f, 0.42625f, -0.88688f, 0.48063f,
            -0.86813f, 0.53188f, -0.84688f, 0.58125f, -0.82313f, 0.62750f, -0.79688f, 0.67188f, -0.76812f, 0.71375f,
            -0.73750f, 0.75313f, -0.70375f, 0.79000f, -0.66813f, 0.82438f, -0.62938f, 0.85625f, -0.58875f, 0.88562f,
            -0.54563f, 0.91312f, -0.50000f, 0.93750f
        };
    }
}
